using cCoder.Data;
using cCoder.Packaging.Brokers;
using cCoder.Packaging.Models;
using cCoder.Data.Models.Packaging;
using cCoder.Packaging.Services.Processings;

namespace cCoder.Packaging.Services.Orchestrations;

internal class PackageOrchestrationService(IAppDomainProvider appDomainProvider, IPackageProcessingService processingService, IPackageEventProcessingService eventService, Config config) : IPackageOrchestrationService
{
    public IEnumerable<cCoder.Data.Models.Packaging.Package> Export(int appId, string[] packageNames = null)
    {
        if (packageNames == null || packageNames.Length == 0)
        {
            packageNames = new string[12]
            {
                "Roles", "Layouts", "Templates", "Resources", "Pages", "Workflows", "Components", "Scripts", "PageRoles", "FolderRoles",
                "Calendars", "CalendarEvents"
            };
        }
        List<cCoder.Data.Models.Packaging.Package> list = (from package in processingService.ExportPackages(appId, packageNames)
                                                      select package).ToList();
        string value2;
        string value = (config.Settings.TryGetValue("sslPort", out value2) ? value2 : "443");
        string sourceApi = $"https://{appDomainProvider.GetDomain(appId)}:{value}/Api/";
        list.ForEach(delegate (cCoder.Data.Models.Packaging.Package package)
        {
            package.Description = "Generated by App export.";
            package.Category = "Dynamic";
            package.SourceApi = sourceApi;
        });
        return list;
    }

    public ValueTask ImportPackageAsync(int appId, cCoder.Data.Models.Packaging.Package package)
    {
        return eventService.RaisePackageImportEventAsync(appId, package);
    }

    public cCoder.Data.Models.Packaging.Package Get(Guid id)
    {
        return processingService.Get(id);
    }

    public IQueryable<cCoder.Data.Models.Packaging.Package> GetAll(bool ignoreFilters = false)
    {
        return processingService.GetAll(ignoreFilters);
    }

    public async ValueTask<cCoder.Data.Models.Packaging.Package> AddAsync(cCoder.Data.Models.Packaging.Package entity)
    {
        cCoder.Data.Models.Packaging.Package result = await processingService.AddAsync(entity);
        await eventService.RaisePackageAddEventAsync(result);
        return result;
    }

    public async ValueTask<cCoder.Data.Models.Packaging.Package> UpdateAsync(cCoder.Data.Models.Packaging.Package entity)
    {
        cCoder.Data.Models.Packaging.Package result = await processingService.UpdateAsync(entity);
        await eventService.RaisePackageUpdateEventAsync(result);
        return result;
    }

    public async ValueTask DeleteAsync(Guid id)
    {
        cCoder.Data.Models.Packaging.Package entity = processingService.Get(id);
        await eventService.RaisePackageDeleteEventAsync(entity);
        await processingService.DeleteAsync(id);
    }

    public async ValueTask<IEnumerable<Result<cCoder.Data.Models.Packaging.Package>>> AddOrUpdate(IEnumerable<cCoder.Data.Models.Packaging.Package> items)
    {
        return (await processingService.AddOrUpdate(items)).ToArray();
    }

    public ValueTask DeleteAllAsync(IEnumerable<cCoder.Data.Models.Packaging.Package> items)
    {
        return processingService.DeleteAllAsync(items);
    }
}
