// ---------------------------------------------------------------
// Copyright (c) Paul.Ward@ccoder.co.uk
// ---------------------------------------------------------------

using cCoder.Data;
using cCoder.Data.Extensions;
using cCoder.Packaging.Brokers;
using cCoder.Packaging.Models;
using cCoder.Data.Models.Packaging;
using cCoder.Packaging.Services.Processings;

namespace cCoder.Packaging.Services.Orchestrations;

internal class PackageOrchestrationService(
    IAppDomainProvider appDomainProvider,
    IPackageProcessingService processingService,
    IPackageItemProcessingService packageItemProcessingService,
    IPackageEventProcessingService eventService,
    Config config)
    : IPackageOrchestrationService
{
    public IEnumerable<cCoder.Data.Models.Packaging.Package> Export(int appId, string[] packageNames = null)
    {
        if (packageNames == null || packageNames.Length == 0)
        {
            packageNames = new string[12]
            {
                "Roles", "Layouts", "Templates", "Resources", "Pages", "Workflows", "Components", "Scripts", "PageRoles", "FolderRoles",
                "Calendars", "CalendarEvents"
            };
        }

        List<cCoder.Data.Models.Packaging.Package> list = (from package in processingService.ExportPackages(appId: appId, packageNames: packageNames)
                                                           select package).ToList();

        string value2;
        string value = (config.Settings.TryGetValue(key: "sslPort", out value2) ? value2 : "443");
        string sourceApi = $"https://{appDomainProvider.GetDomain(appId: appId)}:{value}/Api/";

        list.ForEach(action: delegate (cCoder.Data.Models.Packaging.Package package)
        {
            package.Description = "Generated by App export.";
            package.Category = "Dynamic";
            package.SourceApi = sourceApi;
        });

        return list;
    }

    public ValueTask ImportPackageAsync(int appId, cCoder.Data.Models.Packaging.Package package)
    {
        return eventService.RaisePackageImportEventAsync(appId: appId, package: package);
    }

    public cCoder.Data.Models.Packaging.Package Get(Guid id)
    {
        return processingService.GetPackage(packageId: id);
    }

    public IQueryable<cCoder.Data.Models.Packaging.Package> GetAll(bool ignoreFilters = false)
    {
        return processingService.GetAllPackages(ignoreFilters: ignoreFilters);
    }

    public async ValueTask<cCoder.Data.Models.Packaging.Package> AddAsync(cCoder.Data.Models.Packaging.Package entity)
    {
        cCoder.Data.Models.Packaging.Package result =
            await processingService.AddPackageAsync(newPackage: entity);
        await eventService.RaisePackageAddEventAsync(newPackage: result);
        return result;
    }

    public async ValueTask<cCoder.Data.Models.Packaging.Package> UpdateAsync(cCoder.Data.Models.Packaging.Package entity)
    {
        cCoder.Data.Models.Packaging.Package result =
            await processingService.UpdatePackageAsync(updatedPackage: entity);

        if (entity.Items is not null && entity.Items.Any())
        {
            PackageItem[] deletedPackageItems = packageItemProcessingService
                .GetAllPackageItems()
                .Where(predicate: packageItem => packageItem.PackageId == result.Id)
                .ToArray();

            await packageItemProcessingService
                .DeleteAllPackageItemsAsync(deletedPackageItems: deletedPackageItems);

            entity.Items.ForEach(action: packageItem =>
            {
                packageItem.PackageId = result.Id;
            });

            await packageItemProcessingService
                .AddOrUpdatePackageItemsAsync(packageItems: entity.Items);
        }

        await eventService.RaisePackageUpdateEventAsync(updatedPackage: result);
        return result;
    }

    public async ValueTask DeleteAsync(Guid id)
    {
        cCoder.Data.Models.Packaging.Package entity =
            processingService.GetPackage(packageId: id);
        await eventService.RaisePackageDeleteEventAsync(deletedPackage: entity);
        await processingService.DeletePackageAsync(packageId: id);
    }

    public async ValueTask<IEnumerable<Result<cCoder.Data.Models.Packaging.Package>>> AddOrUpdate(IEnumerable<cCoder.Data.Models.Packaging.Package> items)
    {
        List<Result<Package>> results = [];

        foreach (Package package in items)
        {
            try
            {
                bool isNewPackage = package.Id == Guid.Empty;
                Package savedPackage = isNewPackage
                    ? await processingService.AddPackageAsync(newPackage: package)
                    : await processingService.UpdatePackageAsync(updatedPackage: package);

                results.Add(item: new Result<Package>
                {
                    Success = true,
                    Item = savedPackage,
                    Message = isNewPackage
                        ? "Added Successfully"
                        : "Updated Successfully",
                });
            }
            catch (Exception exception)
            {
                results.Add(item: new Result<Package>
                {
                    Success = false,
                    Item = package,
                    Message = exception.Message,
                });
            }
        }

        return results;
    }

    public ValueTask DeleteAllAsync(IEnumerable<cCoder.Data.Models.Packaging.Package> items)
    {
        return DeletePackagesAsync(items: items);
    }

    private async ValueTask DeletePackagesAsync(IEnumerable<Package> items)
    {
        foreach (Package package in items)
        {
            await processingService.DeletePackageAsync(packageId: package.Id);
        }
    }
}
